# Generated by Django 3.0.1 on 2020-01-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20200109_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('stw', models.FileField(upload_to='software_upload/stws')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
