# Generated by Django 3.0.1 on 2020-01-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='softdes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_name', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('version', models.IntegerField()),
                ('hardware_req', models.TextField()),
                ('date', models.DateTimeField(verbose_name='uploaded date')),
            ],
        ),
    ]
