# Generated by Django 3.0.1 on 2020-01-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_auto_20200123_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='stw',
            field=models.FileField(upload_to='software_upload/stw'),
        ),
    ]
